services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    networks:
      - docker_network
    depends_on:
      - wordpress
    volumes:
      - dataContainer:/var/www/html
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    networks:
      - docker_network
    volumes:
      - mariadbData:/var/lib/mysql
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    ports:
      - 9000:9000
    restart: always
    env_file:
      - .env
    networks:
      - docker_network
    depends_on:
      - mariadb
    volumes:
      - dataContainer:/var/www/html
networks:
  docker_network:
    name: docker_network
volumes:
  dataContainer:
    driver: local
    name: dataContainer
    driver_opts:
      type: none
      device: /home/mel-mars/data/wordpress
      o: bind
  mariadbData:
    driver: local
    name: mariadbData
    driver_opts:
      type: none
      device: /home/mel-mars/data/mariadb
      o: bind
