version: "3"
services:
  nginx:
    build: ./nginx
    image: nginx
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    networks:
      - docker_network
  mariadb:
    build: ./mariadb
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    networks:
      - docker_network
  wordpress:
      build: ./wordpress
      image: wordpress
      ports:
        - 9000:9000
      restart: always
      env_file:
        - .env
      networks:
        - docker_network
networks:
  docker_network:
    name: docker_network
    driver: bridge