version: "3.8"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    networks:
      - docker_network
    depends_on:
      - wordpress
    volumes:
      - dataContainer:/var/www/html
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    networks:
      - docker_network
  wordpress:
      build: ./wordpress
      container_name: wordpress
      image: wordpress
      ports:
        - 9000:9000
      restart: always
      env_file:
        - .env
      networks:
        - docker_network
      depends_on:
        - mariadb
      volumes:
        - dataContainer:/var/www/html
networks:
  docker_network:
    name: docker_network
    driver: bridge
volumes:
  dataContainer:
    driver: local
    name: dataContainer
    driver_opts:
      type: none
      device: /home/mm/data/wordpress
      o: bind